### ISSUE TITLE
Extension not working for me

### ISSUE THREAD

**Issue by omcknightkittl** [RobinPicard/metabase-chatgpt#10]
Hey, 

I have installed the chrome extension and put in my api key. However, I do not see any of the buttons that are shown in your video. Metabase - ChatGPT - version 1.5. 

My company uses a Metabse version of  0.46.6.1. I am not hosting metabse on my local host like you are in the video so that could be the issue? 

I am not comfortable sharing my companies metabse url. 

Thanks, Oisin

**Comment by RobinPicard** [comment]
Hi @omcknightkittl! Thanks for raising an issue. The extension script is injected for urls that follow this condition:
```
url.includes("/question")
&& (
  url.includes("metabase")
  || url.includes("localhost")
  || url.includes("127.0.0.1")
)
```
I guess the issue is that your company's Metabase url does not contain the word metabase at all. If that's the case, we could probably look into letting the user specify their Metabase url in the popup and add it dynamically to the condition above

**Comment by omcknightkittl** [comment]
Ah I see, yes it only has the word "meta" in it.  Your solution makes sense for sure. Any chance you can just include "meta" in the code above or is that a risk of it attempting to work on meta.com

**Comment by RobinPicard** [comment]
Yes, I can just change it to "meta" as there's the other condition on "/question" that should greatly limit false positives. I think I'll wait for another user to raise a similar issue with a funky url before implementing what I proposed above as I would rather not make the popup of the extension more crowded than it already is. I'll submit the new version tonight and it should be available in around 2 days (average time for Google to review)

**Comment by omcknightkittl** [comment]
Thank you so much Robin!

**Comment by omcknightkittl** [comment]
Hey Robin,

That worked for me by the way. Its working well. I am very impressed.

One thing, how do you see this from a data security perspective? Should I
be concerned about letting the bot read my metadata?

**Comment by RobinPicard** [comment]
Hi Oisin,

Thanks, I'm glad it's working well.
Regarding security, the extension does not have any server nor database, so
the only 2 entities involved are your browser and OpenAI.
What's passed on to OpenAI when you submit a prompt is:
- the prompt itself
- the SQL query if there was any
- a description of the 3 most relevant tables of your database (with the
name of the columns) if you have turned on the "database structure
embedding" option in the settings.
I guess it's the last one you're concerned about. With it, you do provide
some information regarding your database structure to OpenAI but no actual
data is sent. So, OpenAI will get absolutely nothing about your users or
customers for instance.
I hope this clears things up!

Best,
Robin

PS: if you find the extension useful, feel free to give it a star on Github
and to rate it on the Chrome store!



Le jeu. 17 août 2023 à 14:37, Oisin McKnight ***@***.***> a
écrit :

> Hey Robin,
>
> That worked for me by the way. Its working well. I am very impressed.
>
> One thing, how do you see this from a data security perspective? Should I
> be concerned about letting the bot read my metadata?
>

**Comment by omcknightkittl** [comment]
Hey @RobinPicard , 

The same issue is happening again where anyone in my company cannot see the buttons. 

Could it be the same issue? or url has not changed. Still starts with meta.kittl

**Comment by RobinPicard** [comment]
Hi @omcknightkittl! I doubt it's the same issue if your url has not changed. Maybe a recent update from Metabase changed something. Do you know what version you're using?

**Comment by behrsons** [comment]
Hey @RobinPicard, we are using v0.48.0

"You're on version v0.48.0
Built on 2023-12-14" 

cc @omcknightkittl

**Comment by RobinPicard** [comment]
Fix here: https://github.com/RobinPicard/metabase-chatgpt/pull/13, although it'll take a few days to be available in the Chrome store as usual. @behrsons @omcknightkittl

**Comment by RobinPicard** [comment]
Is it working fine now? @behrsons  @omcknightkittl
