### ISSUE TITLE
could not load icon

### ISSUE THREAD

**Issue by bodhanam123** [RobinPicard/metabase-chatgpt#12]
when adding extension to chrome it is showing error as below

Package is invalid. Details: 'Could not load icon 'chrome_icons/icon48.png' specified in 'icons'.'.

**Comment by RobinPicard** [comment]
Hi bodhanam123. Is it when downloading from the store or when loading the unpacked extension? Could you provide screenshots please?

**Comment by RobinPicard** [comment]
It was an issue with the capitalization of the icon name, fixed
