### ISSUE TITLE
A History modal for the already executed queries.

### ISSUE THREAD

**Issue by pike-py** [RobinPicard/metabase-chatgpt#18]
Considering that each hit to the OpenAI has some cost, it would be better if we could also store the already executed queries. 
To make it more useful we can let the user decide which queries they want to add in the history modal.

Let me know if you like the idea?

**Comment by RobinPicard** [comment]
Hi @pike-py! Thanks for opening an issue.

My first reaction would be to think that the benefits are not important enough to justify the added complexity. Some reasons for which I think so:
- The prompts would need to be exactly the same (down to each character), does that really happen that often?
- The costs per query are quite low (cents at most), so if this situation does not happen that often the savings would be limited.
- Many people just save the question if they often need to make the same query

Does that make sense to you?

PS: I just merged a new version (2.0) that includes an estimation of the cost per query based on the user's database, maybe you would find it interesting as you're concerned about costs

**Comment by pike-py** [comment]
Thank you for your thoughts on this!!
Now that you have put it this way, it feels fairly reasonable to not add extra complexity.

I have had few interactions with the users at my end and they wanted similar feature along with some extra tweaks. Currently i am doing a few modifications in the source code of yours for the same.

Appreciate your work  that you have put up on this extension.
And thank you for letting me know about the new version. Will give it a try.
