### ISSUE TITLE
Doesn't work on Metabase 0.46.4?

### ISSUE THREAD

**Issue by Sire** [RobinPicard/metabase-chatgpt#5]
I've enabled the plugin on all sites, entered API key and no extra buttons are showing up.
Running latest Metabase (open source) 0.46.4, is this the problem?

**Comment by RobinPicard** [comment]
Hi Sire. I did not notice any problem when downloading the latest jar file a few weeks ago. Have you tried just refreshing the page or trying in a new window? In a few instances I've also had the buttons not showing up and trying again later solved it. I guess there's a little bug somewhere but I don't know where

**Comment by jeankri** [comment]
Bonjour 

Je teste actuellement votre extension et j'ai le même pb
pas d'affichage des boutons

merci d'avance

**Comment by RobinPicard** [comment]
Hello @Sire and @jeankri. I may know what's going on. I've tried again using v.0.46 locally (downloaded here: https://www.metabase.com/docs/latest/installation-and-operation/running-the-metabase-jar-file) and realized that the extension does not work because it's set to inject the script in the page only when the url contains the word "metabase" (see the file `background.js`). Since I was running it at `localhost:3000`, it was not working. I assumed "metabase" would always be in the url but it seems I was wrong. Is it the case for you?

**Comment by Sire** [comment]
Yes, this must be it. Good catch!

**Comment by jeankri** [comment]
Hello it s ok for me with metabase in the url

But when i use

[image: image.png]



[image: image.png]

Openai indicated that your API key is no long valid, please modify it in
the extension's popup
The error message they provided: The model: `gpt-4` does not exist
*/


thanks



<https://streaklinks.com/Bk76ajDfn9yy5pDgeAc6TzIu/https%3A%2F%2Fcard.pm%2Fgoodit%2Fjean-christophe.rimbaud>

ᐧ

Le sam. 8 juil. 2023 à 17:18, Robin Picard ***@***.***> a
écrit :

**Comment by RobinPicard** [comment]
I can't see your images @jeankri

**Comment by jeankri** [comment]
Hello it s ok for me with metabase in the url

But when i use 

![image](https://github.com/RobinPicard/metabase-chatgpt/assets/70752818/d6c19a95-6f71-4d7e-9902-56c68dcab997)


![image](https://github.com/RobinPicard/metabase-chatgpt/assets/70752818/24f8444c-74d0-4fd1-bef4-258e247dc8df)

the message
Openai indicated that your API key is no long valid, please modify it in the extension's popup
The error message they provided: The model: `gpt-4` does not exist

**Comment by jeankri** [comment]
Hello

i put the screen on github






<https://streaklinks.com/Bk8DJRBW1kPnPz6F5gAQbfg9/https%3A%2F%2Fcard.pm%2Fgoodit%2Fjean-christophe.rimbaud>

ᐧ

Le lun. 10 juil. 2023 à 11:28, Robin Picard ***@***.***> a
écrit :

**Comment by RobinPicard** [comment]
Ah that's an issue with the name of the model I provide the Openai API, I'll change that soon. Thanks for letting me know about it @jeankri! Taking into account the review time from Google, the fix will be available only in a few days though

**Comment by RobinPicard** [comment]
There's this open PR to let the user choose the model version of chatgpt they want @jeankri: https://github.com/RobinPicard/metabase-chatgpt/pull/7. Hopefully it'll solve your issue by letting you choose 3.5 instead of 4
